### ISSUE TITLE
can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Mte90** [msr8/markify#1]
![Screenshot_20220822_182524](https://user-images.githubusercontent.com/403283/185971158-dedf0ae7-8986-4c9b-b5f9-fa2c95c216c3.png)

As you can see I get that error.

**Comment by Mte90** [comment]
Patched in this way and now works:

![immagine](https://user-images.githubusercontent.com/403283/185971846-42ffd11d-2d0e-40a4-bcc0-4c05f5d57aa3.png)

I just see that is blocked at 26%, when is downloading those stuff download at the end or during? Just because I don't want to restart for testing to download it all of them.

```
LOG]      Config keys: reddit, twitter
[LOG]      Getting the newest reddit comments of u/mte90
 26%|████████████████████████████████████████████▋                                                                                                                            | 2642/10000 [00:40<01:32, 79.59it/s]
```

**Comment by msr8** [comment]
Hey there, sorry for the late reply, thank you for this information! I did some digging and looks like `dic.get('permalink')` returns `None` only for some specific subreddits, could be an issue with pushshift. Are you by any chance banned in [r/italy](https://reddit.com/r/italy) or [r/firefox](https://reddit.com/r/firefox)?

<br>

> I just see that is blocked at 26%, when is downloading those stuff download at the end or during? Just because I don't want to restart for testing to download it all of them.

Can you please elaborate on what you mean? If you're asking when the data gets saved, it gets saved after it is done scraping a platform. Like it saves all the reddit comments once all of them are scraped. Then it moves on to discord and saves all the messages only when all the messages have been scraped. Same with twitter

**Comment by Mte90** [comment]
No I am not banned but maybe some of those thread where removed? I am not sure

My question about saving was that it was crashing around that percentage so it required to start from 0 again as doesn't save them during the process but only at the end.

**Comment by msr8** [comment]
> My question about saving was that it was crashing around that percentage so it required to start from 0 again as doesn't save them during the process but only at the end.

Yupp, I am afraid that you would have to restart the program, but it should be fixed now

> No I am not banned but maybe some of those thread where removed? I am not sure

Hmm, smells like a pushshift issue then, cause there are a LOT of instances of `None` being returned, and pushshift is supposed to preserve the links even if the threads get deleted as far as i am aware
