### ISSUE TITLE
Discord scraping

### ISSUE THREAD

**Issue by ytalp17** [msr8/markify#3]
Hey there, 
First and foremost seems like a decent repository, thank you for making it public.
I experimented with it, and if I understood correctly it only scrapes all of your DMs through different servers.

Do you know whether it is possible to scrape full messages on a Discord server?

Thank you!

**Comment by msr8** [comment]
> First and foremost seems like a decent repository, thank you for making it public

Thank you, I appreciate that :)

> I experimented with it, and if I understood correctly it only scrapes all of your DMs through different servers

Yupp, discord refers to the DMs as "channels"

> Do you know whether it is possible to scrape full messages on a Discord server?

By a "discord server", do you mean a proper discord server with multiple users or just a DM channel between two users? It is possible to do both, but my recommended approach would vary on that basis

**Comment by ytalp17** [comment]
I meant a proper discord server with multiple users. More specifically, I want to scrape a specific channel (i.e room) under a discord server.Do you think it is possible? Is there scriptable word limit as it is the case with DM channels?

Thank you!

**Comment by msr8** [comment]
See when I made this project, there wasnt the `before` parameter in the `/channels/{channel.id}/messages` endpoint, but now there is. So what you can do is get the latest 100 messages and store the message ID of the oldest message (from those 100 messages) and put that value in the `before` parameter, and keep doing this until you get a response with no messages (meaning you have already gone through all the messages). For more info about this `before` parameter, here are the official docs regarding it: https://discord.com/developers/docs/resources/channel#get-channel-messages
